# Generated by Django 5.1 on 2024-10-08 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0003_auto_20240610_1806"),
    ]

    operations = [
        migrations.CreateModel(
            name="Number",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.IntegerField(unique=True)),
                ("definition", models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name="Word",
        ),
    ]
